### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by rfdickerson** [neich/rust-cql#10]
Hello, we would like to use this library for a project in an open source project at IBM, but we need a LICENSE file in the repo to move forward with using this library. Can you add one for us at your convenience? Most licenses like MIT, Apache 2, etc will work.

Thanks!

**Comment by neich** [comment]
Done. I've added a MIT license file.

BTW, beware that a big PR is coming from one of my students. There will be very basic support for load balancing and node autodiscovery, but still in alpha stage ...

**Comment by neich** [comment]
I've already accepted the PR, but it is on branch `mio`. It is a completely new library since now it is an asynchronous client using Futures (eventual + mio crates). I will soon merge the `mio` branch into `master`, so the library will change completely.

**Comment by rfdickerson** [comment]
Thanks @neich . Will be be learning from your work here. We are creating a pure Swift adapter similar to what you did here for Rust. :)
